### PR TITLE
Update

### PR DESCRIPTION
**Pull request by mrpiper21**
1. I created a new folder "controller"; In the adminController.js i have created different modules to handle the request as intended and of course i exported them
2.  in the initial admin file which i later want to change it to adminRoute.js, I have created a router and imported the modules from the controller to perform the task as intended
3. I have also created different modules to handle the data base connection and also the socket connection

This should make the code easier to read an understand

NOTE: I RECOMMEND YOU GO THROUGH ALL THE CHANGES BEFORE MERGING THE REQUEST, I MIGHT HAVE NOT INCLUDED SOME MODULES THE IMPLEMENTED SOME FUNCTIONS AS INTENDED

### CODE REVIEW

**Comment by Aburafik** [comment]
Alright

**Comment by Aburafik** [comment]
You can also test at your end with any of the endpoints on postman using localhost.

**Comment by mrpiper21** [comment]
checkout the new update

**Comment by mrpiper21** [comment]
For some reasons the .env is still is the repository even though i included it in the gitignore file. Check to see if you can rectify it

**Comment by Aburafik** [comment]
> For some reasons the .env is still is the repository even though i included it in the gitignore file. Check to see if you can rectify it

**Pull request merged**
